#! /usr/bin/env python
import csv
import argparse
from os import path 
import datetime


def main(argv=None):

    argumentValues = checkArgumentValidity(argv)
    filePath = argumentValues[0]
    targetDate = argumentValues[1]
    # list to store all the cookies given on the target date 
    cookiesOnTargetDate = []




    return -1




def checkArgumentValidity(argv):

    # parse command line into Python data types 
    argparser = argparse.ArgumentParser(description="Find the most active cookie given a cookie log file and a date")
    argparser.add_argument(dest="filePath", help="File path to cookie log CSV")
    argparser.add_argument('-d', dest="targetDate", help="Target date to find cookie")

    # save file arguments into variables
    args = argparser.parse_args()
    filePath = args.filePath
    targetDate = args.targetDate

    # test if all necessary arguments (file path and target date) are input by the user
    # if not, raise necessary exceptions to show an error has occured 
    if not path.exists(filePath):
        raise Exception("Invalid file path")
    if targetDate == None:
        raise Exception("Please input a target date as argument")
    # validate the target date argument using datetime library
    try:
        datetime.datetime.strptime(targetDate, '%Y-%m-%d')
    except ValueError:
        raise ValueError("Incorrect date format, should be YYYY-MM-DD")
    
    # return filePath and targetDate to be used in main function
    return [filePath, targetDate]


if __name__ == "__main__":
    main()

